# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'mobile' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'mobileTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Fix for Xcode 16.3 std::char_traits<unsigned char> error
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable pedantic warnings that cause C++ STL issues
        config.build_settings['GCC_WARN_PEDANTIC'] = 'NO'
        config.build_settings['CLANG_WARN_PEDANTIC'] = 'NO'
        config.build_settings['GCC_TREAT_WARNINGS_AS_ERRORS'] = 'NO'

        # Force C++20 for better char_traits support
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++20'

        # Add preprocessor definition to work around the issue
        existing_defs = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] || ['$(inherited)']
        unless existing_defs.is_a?(Array)
          existing_defs = [existing_defs]
        end
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = existing_defs + ['FOLLY_NO_CONFIG=1', 'FOLLY_CFG_NO_COROUTINES=1', 'FOLLY_HAVE_CLOCK_GETTIME=1']
      end
    end
  end
end
